complexity:
  LongMethod:
    excludes: ['**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/jsTest/**', '**/iosTest/**']

naming:
  FunctionNaming:
    ignoreAnnotated:
      - "Composable"

style:
  ForbiddenComment:
    active: true
    values:
      - 'FIXME:'
      - 'STOPSHIP:'
  MagicNumber:
    active: false
