naming:
  FunctionNaming:
    active: false # TODO: https://github.com/detekt/detekt/issues/4230
    ignoreAnnotated:
      - "Composable"

style:
  ForbiddenComment:
    active: true
    values:
      - 'FIXME:'
      - 'STOPSHIP:'
  MagicNumber:
    active: false
  UnusedPrivateClass:
    ignoreAnnotated:
      - "ExcludeFromJacocoGeneratedReport"
