comments:
  AbsentOrWrongFileLicense:
    active: true
    excludes: [ '**/generated/**' ]

complexity:
  LongMethod:
    excludes: [ '**/test/**', '**/androidTest/**', '**/sharedTest/**', '**/commonTest/**', '**/jvmTest/**', '**/jsTest/**', '**/iosTest/**' ]

formatting:
  Indentation:
    excludes: [ '**/generated/**' ]
  NoConsecutiveBlankLines:
    excludes: [ '**/generated/**' ]
  NoLineBreakBeforeAssignment:
    excludes: [ '**/generated/**' ]

naming:
  ClassNaming:
    excludes: [ '**/generated/**' ]
  FunctionNaming:
    ignoreAnnotated:
      - "Composable"
    excludes: [ '**/test/**', '**/androidTest/**', '**/sharedTest/**', '**/commonTest/**', '**/jvmTest/**', '**/jsTest/**', '**/iosTest/**' ]
  MatchingDeclarationName:
    excludes: [ '**/generated/**' ]
  TopLevelPropertyNaming:
    excludes: [ '**/generated/**' ]

style:
  ForbiddenComment:
    active: true
    values:
      - 'FIXME:'
      - 'STOPSHIP:'
  ForbiddenImport:
    active: true
    imports:
      - 'org.junit.jupiter.api.Assertions.*'
      - 'org.junit.jupiter.api.fail'
      - 'org.junit.jupiter.api.assert*'
      - 'org.junit.Assert.*'
  MagicNumber:
    active: false
