comments:
  AbsentOrWrongFileLicense:
    active: true
    excludes: [ '**/generated/**' ]

complexity:
  LongMethod:
    excludes: [ '**/test/**', '**/androidTest/**', '**/sharedTest/**', '**/commonTest/**', '**/jvmTest/**', '**/jsTest/**', '**/iosTest/**' ]

empty-blocks:
  EmptyKtFile:
    excludes: [ '**/generated/**' ]

formatting:
  CommentSpacing:
    excludes: [ '**/generated/**' ]
  FunKeywordSpacing:
    active: true
  Indentation:
    excludes: [ '**/generated/**' ]
  MaximumLineLength:
    excludes: [ '**/generated/**' ]
  ModifierListSpacing:
    active: true
  NoConsecutiveBlankLines:
    excludes: [ '**/generated/**' ]
  NoEmptyFirstLineInMethodBlock:
    active: true
  NoLineBreakBeforeAssignment:
    excludes: [ '**/generated/**' ]
  NoSemicolons:
    excludes: [ '**/generated/**' ]
  ParameterListWrapping:
    excludes: [ '**/generated/**' ]
  SpacingAroundAngleBrackets:
    active: true
  SpacingAroundCurly:
    excludes: [ '**/generated/**' ]
  TrailingComma:
    active: true
    autocorrect: true
    allowTrailingComma: true
    allowTrailingCommaOnCallSite: true
    excludes: [ '**/generated/**' ]
  UnnecessaryParenthesesBeforeTrailingLambda:
    active: true
  Wrapping:
    excludes: [ '**/generated/**' ]

naming:
  ConstructorParameterNaming:
    excludes: [ '**/generated/**' ]
  ClassNaming:
    excludes: [ '**/generated/**' ]
  FunctionNaming:
    active: false
  MatchingDeclarationName:
    excludes: [ '**/generated/**' ]
  TopLevelPropertyNaming:
    excludes: [ '**/generated/**' ]

style:
  ForbiddenComment:
    active: true
    values:
      - 'FIXME:'
      - 'STOPSHIP:'
  ForbiddenImport:
    active: true
    imports:
      - 'org.junit.jupiter.api.Assertions.*'
      - 'org.junit.jupiter.api.fail'
      - 'org.junit.jupiter.api.assert*'
      - 'org.junit.Assert.*'
  MaxLineLength:
    excludes: [ '**/generated/**' ]
  MagicNumber:
    active: false
