comments:
  AbsentOrWrongFileLicense:
    active: true
    excludes: [ '**/generated/**' ]
    licenseTemplateIsRegex: true

complexity:
  LongMethod:
    excludes: [
      '**/test/**',
      '**/androidTest/**',
      '**/sharedTest/**',
      '**/commonTest/**',
      '**/jvmTest/**',
      '**/androidAndroidTest/**',
      '**/androidSharedTest/**',
      '**/jsTest/**',
      '**/iosTest/**'
    ]
  LongParameterList:
    excludes: [ '**/generated/**' ]
  TooManyFunctions:
    excludes: [
      '**/generated/**',
      '**/test/**',
      '**/androidTest/**',
      '**/sharedTest/**',
      '**/commonTest/**',
      '**/jvmTest/**',
      '**/androidAndroidTest/**',
      '**/androidSharedTest/**',
      '**/jsTest/**',
      '**/iosTest/**'
    ]

empty-blocks:
  EmptyDefaultConstructor:
    excludes: [ '**/generated/**' ]
  EmptyKtFile:
    excludes: [ '**/generated/**' ]

formatting:
  ArgumentListWrapping:
    excludes: [ '**/generated/**' ]
  CommentSpacing:
    excludes: [ '**/generated/**' ]
  EnumEntryNameCase:
    excludes: [ '**/generated/**' ]
  Filename:
    excludes: [ '**/generated/**' ]
  FunKeywordSpacing:
    active: true
  ImportOrdering:
    excludes: [ '**/generated/**' ]
  Indentation:
    excludes: [ '**/generated/**' ]
  MaximumLineLength:
    excludes: [ '**/generated/**' ]
  MultiLineIfElse:
    excludes: [ '**/generated/**' ]
  ModifierListSpacing:
    active: true
  NoConsecutiveBlankLines:
    excludes: [ '**/generated/**' ]
  NoEmptyFirstLineInMethodBlock:
    active: true
  NoLineBreakBeforeAssignment:
    excludes: [ '**/generated/**' ]
  NoMultipleSpaces:
    excludes: [ '**/generated/**' ]
  NoSemicolons:
    excludes: [ '**/generated/**' ]
  NoTrailingSpaces:
    excludes: [ '**/generated/**' ]
  NoUnitReturn:
    excludes: [ '**/generated/**' ]
  ParameterListWrapping:
    excludes: [ '**/generated/**' ]
  SpacingAroundAngleBrackets:
    active: true
  SpacingAroundCurly:
    excludes: [ '**/generated/**' ]
  TrailingCommaOnCallSite:
    active: false
    autoCorrect: true
    useTrailingCommaOnCallSite: false
    excludes: [ '**/generated/**' ]
  TrailingCommaOnDeclarationSite:
    active: false
    autoCorrect: true
    useTrailingCommaOnDeclarationSite: false
    excludes: [ '**/generated/**' ]
  UnnecessaryParenthesesBeforeTrailingLambda:
    active: true
  Wrapping:
    excludes: [ '**/generated/**' ]

naming:
  ConstructorParameterNaming:
    excludes: [ '**/generated/**' ]
  ClassNaming:
    excludes: [ '**/generated/**' ]
  FunctionNaming:
    active: false
  FunctionParameterNaming:
    excludes: [ '**/generated/**' ]
  MatchingDeclarationName:
    excludes: [ '**/generated/**' ]
  ObjectPropertyNaming:
    excludes: [ '**/generated/**' ]
  TopLevelPropertyNaming:
    excludes: [ '**/generated/**' ]
  VariableNaming:
    excludes: [ '**/generated/**' ]

style:
  ForbiddenComment:
    active: true
    values:
      - 'FIXME:'
      - 'STOPSHIP:'
  ForbiddenImport:
    active: true
    imports:
      # Disallow JUnit5 imports in favor of kotlin.test
      - 'org.junit.jupiter.api.Assertions.*'
      - 'org.junit.jupiter.api.Test'
      - 'org.junit.jupiter.api.fail'
      - 'org.junit.jupiter.api.assert*'
      # Disallow JUnit4 imports in favor of kotlin.test
      - 'org.junit.Test'
      - 'org.junit.Assert.*'
      # Disallow JUnit5 parameterized tests in favor of TestParameterInjector
      - 'org.junit.jupiter.params.*'
  MaxLineLength:
    excludes: [ '**/generated/**' ]
  MagicNumber:
    active: false
