comments:
  AbsentOrWrongFileLicense:
    active: true
    excludes: [ '**/generated/**' ]
    licenseTemplateIsRegex: true

complexity:
  CyclomaticComplexMethod:
    excludes: [ '**/generated/**' ]
  LargeClass:
    excludes: [ '**/generated/**' ]
  LongMethod:
    excludes: [
      '**/generated/**',
      '**/commonTest/**',
      '**/jvmTest/**',
      '**/desktopTest/**',
      '**/desktopMoleculeTest/**',
      '**/androidInstrumentedTest/**',
      '**/androidSharedTest/**',
      '**/androidUnitTest/**',
      '**/jsTest/**',
      '**/iosTest/**'
    ]
  LongParameterList:
    excludes: [ '**/generated/**' ]
  TooManyFunctions:
    excludes: [
      '**/generated/**',
      '**/commonTest/**',
      '**/jvmTest/**',
      '**/desktopTest/**',
      '**/desktopMoleculeTest/**',
      '**/androidInstrumentedTest/**',
      '**/androidSharedTest/**',
      '**/androidUnitTest/**',
      '**/jsTest/**',
      '**/iosTest/**'
    ]

empty-blocks:
  EmptyDefaultConstructor:
    excludes: [ '**/generated/**' ]
  EmptyFunctionBlock:
    excludes: [ '**/generated/**' ]
  EmptyKtFile:
    excludes: [ '**/generated/**' ]

exceptions:
  SwallowedException:
    excludes: [ '**/generated/**' ]

formatting:
  ArgumentListWrapping:
    excludes: [ '**/generated/**' ]
  CommentSpacing:
    excludes: [ '**/generated/**' ]
  EnumEntryNameCase:
    excludes: [ '**/generated/**' ]
  Filename:
    excludes: [ '**/generated/**' ]
  FunctionReturnTypeSpacing:
    excludes: [ '**/generated/**' ]
  FunctionStartOfBodySpacing:
    excludes: [ '**/generated/**' ]
  FunKeywordSpacing:
    active: true
  ImportOrdering:
    excludes: [ '**/generated/**' ]
  Indentation:
    excludes: [ '**/generated/**' ]
  MaximumLineLength:
    excludes: [ '**/generated/**' ]
  MultiLineIfElse:
    excludes: [ '**/generated/**' ]
  ModifierListSpacing:
    active: true
    excludes: [ '**/generated/**' ]
  NoConsecutiveBlankLines:
    excludes: [ '**/generated/**' ]
  NoEmptyFirstLineInMethodBlock:
    active: true
    excludes: [ '**/generated/**' ]
  NoLineBreakBeforeAssignment:
    excludes: [ '**/generated/**' ]
  NoMultipleSpaces:
    excludes: [ '**/generated/**' ]
  NoSemicolons:
    excludes: [ '**/generated/**' ]
  NoTrailingSpaces:
    excludes: [ '**/generated/**' ]
  NoUnitReturn:
    excludes: [ '**/generated/**' ]
  NoUnusedImports:
    active: false # TODO: Re-enable when context parameters are supported
  PackageName:
    excludes: [ '**/generated/**' ]
  ParameterListWrapping:
    excludes: [ '**/generated/**' ]
  PropertyWrapping:
    excludes: [ '**/generated/**' ]
  SpacingAroundAngleBrackets:
    active: true
  SpacingAroundColon:
    active: false # TODO: Re-enable when context parameters are supported
  SpacingAroundComma:
    excludes: [ '**/generated/**' ]
  SpacingAroundCurly:
    excludes: [ '**/generated/**' ]
  SpacingAroundKeyword:
    excludes: [ '**/generated/**' ]
  SpacingAroundParens:
    excludes: [ '**/generated/**' ]
  TrailingCommaOnCallSite:
    active: true
    autoCorrect: true
    useTrailingCommaOnCallSite: true
    excludes: [ '**/generated/**' ]
  TrailingCommaOnDeclarationSite:
    active: true
    autoCorrect: true
    useTrailingCommaOnDeclarationSite: true
    excludes: [ '**/generated/**' ]
  UnnecessaryParenthesesBeforeTrailingLambda:
    active: true
  Wrapping:
    excludes: [ '**/generated/**' ]
    active: false # TODO: Re-enable when context parameters are supported

naming:
  ConstructorParameterNaming:
    excludes: [ '**/generated/**' ]
  ClassNaming:
    excludes: [ '**/generated/**' ]
  FunctionNaming:
    active: false
  FunctionParameterNaming:
    excludes: [ '**/generated/**' ]
  MatchingDeclarationName:
    excludes: [ '**/generated/**' ]
  ObjectPropertyNaming:
    excludes: [ '**/generated/**' ]
  TopLevelPropertyNaming:
    active: false
    excludes: [ '**/generated/**' ]
  VariableNaming:
    excludes: [ '**/generated/**' ]

style:
  ForbiddenComment:
    active: true
    comments:
      - reason: 'Forbidden FIXME todo marker in comment, please fix the problem.'
        value: 'FIXME:'
      - reason: 'Forbidden STOPSHIP todo marker in comment, please address the problem before shipping the code.'
        value: 'STOPSHIP:'
  ForbiddenImport:
    active: true
    imports:
      # Disallow JUnit5 imports in favor of kotlin.test
      - 'org.junit.jupiter.api.Assertions.*'
      - 'org.junit.jupiter.api.Test'
      - 'org.junit.jupiter.api.fail'
      - 'org.junit.jupiter.api.assert*'
      # Disallow JUnit4 imports in favor of kotlin.test
      - 'org.junit.Test'
      - 'org.junit.Assert.*'
      # Disallow JUnit5 parameterized tests in favor of TestParameterInjector
      - 'org.junit.jupiter.params.*'
      # Disallow android.util.Log in favor of Kermit
      - 'android.util.Log'
      # Disallow Wear Material 2 imports
      - 'androidx.wear.compose.material.*'
  MaxLineLength:
    excludes: [ '**/generated/**' ]
  MagicNumber:
    active: false
  ObjectLiteralToLambda:
    excludes: [ '**/generated/**' ]
  UnusedParameter:
    excludes: [ '**/generated/**' ]
  UnusedPrivateMember:
    ignoreAnnotated:
      - "com.alexvanyo.composelife.ui.util.*Previews"
      - "androidx.compose.ui.tooling.preview.Preview"
  UnusedPrivateProperty:
    excludes: [ '**/generated/**' ]
  UseArrayLiteralsInAnnotations:
    excludes: [ '**/generated/**' ]
  VarCouldBeVal:
    excludes: [ '**/generated/**' ]
