complexity:
  LongMethod:
    excludes: ['**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/jsTest/**', '**/iosTest/**']

formatting:
  Indentation:
    excludes: ['**/generated/**']
  NoConsecutiveBlankLines:
    excludes: ['**/generated/**']

naming:
  FunctionNaming:
    ignoreAnnotated:
      - "Composable"
  MatchingDeclarationName:
    excludes: ['**/generated/**']

style:
  ForbiddenComment:
    active: true
    values:
      - 'FIXME:'
      - 'STOPSHIP:'
  MagicNumber:
    active: false
