/*
 * Copyright 2022 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import com.alexvanyo.composelife.buildlogic.configureTesting
import org.gradle.internal.extensions.stdlib.capitalized

plugins {
    alias(libs.plugins.convention.kotlinMultiplatform)
    alias(libs.plugins.convention.androidLibrary)
    alias(libs.plugins.convention.detekt)
    alias(libs.plugins.gradleDependenciesSorter)
    alias(libs.plugins.testBalloon)
}

kotlin {
    androidLibrary {
        namespace = "com.alexvanyo.composelife.wff.resources"
        minSdk = 33
        configureTesting(this)
        // This library contains no code, so desugaring isn't needed
        enableCoreLibraryDesugaring = false
        lint {
            disable += listOf("IconMissingDensityFolder")
        }
        androidResources { enable = true }
    }
    jvm {}

    sourceSets {
        val jvmTest by getting {
            dependencies {
                implementation(projects.algorithm)
                implementation(projects.dispatchersTestFixtures)
                implementation(projects.geometry)
                implementation(projects.tracingTestFixtures)
                implementation(libs.kotlinx.coroutines.test)
                implementation(libs.testBalloon.framework.core)
                implementation(libs.turbine)
            }
        }
    }
}

private val hourPrefixes = listOf(
    "00",
    "01",
    "02",
    "03",
    "04",
    "05",
    "06",
    "07",
    "08",
    "09",
    "10",
    "11",
    "12",
    "13",
    "14",
    "15",
    "16",
    "17",
    "18",
    "19",
    "20",
    "21",
    "22",
    "23",
    "_1",
    "_2",
    "_3",
    "_4",
    "_5",
    "_6",
    "_7",
    "_8",
    "_9",
)

val minuteDataDirectory = layout.buildDirectory.dir("wff/minuteData")
tasks.withType<Task>().named { it == "jvmTest" }.configureEach {
    hourPrefixes.forEach { hourPrefix ->
        (0..59).forEach { minute ->
            outputs.file(
                minuteDataDirectory.get().file("$hourPrefix:${"%02d".format(minute)}.data")
            )
        }
    }
}

androidComponents {
    hourPrefixes.forEach { hourPrefix ->
        val buildHourOtf = tasks.register("buildHour${hourPrefix}Otf", BuildHourOtf::class) {
            // Minute data files are generated by the jvm tests
            dependsOn("jvmTest")
            minuteDataInputDirectory = minuteDataDirectory
            this.hourPrefix = hourPrefix
            buildScript = layout.projectDirectory.file("scripts/build_hour_otf.py")
            generatedResDirectory = layout.buildDirectory.dir("generated/wff/res")
        }
        onVariants { variant ->
            val capitalizedVariantName = variant.name.capitalized()
            tasks.withType<Task>().named {
                it == "generate${capitalizedVariantName}ResValues" ||
                        it == "process${capitalizedVariantName}NavigationResources"
            }.configureEach {
                dependsOn(buildHourOtf)
            }
            variant.sources.res!!.addGeneratedSourceDirectory(
                buildHourOtf,
                BuildHourOtf::generatedResDirectory,
            )
        }
    }
}

abstract class BuildHourOtf : DefaultTask() {

    @get:InputDirectory
    abstract val minuteDataInputDirectory: DirectoryProperty

    @get:InputFile
    abstract val buildScript: RegularFileProperty

    @get:Input
    abstract val hourPrefix: Property<String>

    @get:OutputDirectory
    abstract val generatedResDirectory: DirectoryProperty

    @get:OutputFile
    val otfFile: Provider<RegularFile> =
        generatedResDirectory.flatMap { outputDirectory ->
            hourPrefix.map {
                outputDirectory.dir("font").file("hour$it.otf")
            }
        }

    @get:Inject
    abstract val execOperations: ExecOperations

    @TaskAction
    fun taskAction() {
        val result = execOperations.exec {
            commandLine(
                listOf(
                    "python3",
                    buildScript.get().asFile.absolutePath,
                    "--hour-prefix",
                    hourPrefix.get(),
                    "--minute-dir",
                    minuteDataInputDirectory.get().asFile.absolutePath,
                    "--output-otf",
                    otfFile.get().asFile.absolutePath,
                )
            )
        }
        result.rethrowFailure()
    }
}
