/*
 * Copyright 2022 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import com.alexvanyo.composelife.buildlogic.configureTesting
import org.gradle.internal.extensions.stdlib.capitalized

plugins {
    alias(libs.plugins.convention.kotlinMultiplatform)
    alias(libs.plugins.convention.androidLibrary)
    alias(libs.plugins.convention.detekt)
    alias(libs.plugins.gradleDependenciesSorter)
    alias(libs.plugins.testBalloon)
}

kotlin {
    androidLibrary {
        namespace = "com.alexvanyo.composelife.wff.resources"
        minSdk = 33
        configureTesting(this)
        // This library contains no code, so desugaring isn't needed
        enableCoreLibraryDesugaring = false
        lint {
            disable += listOf("IconMissingDensityFolder")
        }
        androidResources { enable = true }
    }
    jvm {}

    sourceSets {
        val jvmTest by getting {
            dependencies {
                implementation(projects.algorithm)
                implementation(projects.dispatchersTestFixtures)
                implementation(projects.geometry)
                implementation(projects.tracingTestFixtures)
                implementation(libs.kotlinx.coroutines.test)
                implementation(libs.testBalloon.framework.core)
                implementation(libs.turbine)
            }
        }
    }
}

private val hourPrefixes = listOf(
    "00",
    "01",
    "02",
    "03",
    "04",
    "05",
    "06",
    "07",
    "08",
    "09",
    "10",
    "11",
    "12",
    "13",
    "14",
    "15",
    "16",
    "17",
    "18",
    "19",
    "20",
    "21",
    "22",
    "23",
    "_1",
    "_2",
    "_3",
    "_4",
    "_5",
    "_6",
    "_7",
    "_8",
    "_9",
)

val minuteDataDirectory = layout.buildDirectory.dir("wff/minuteData")
tasks.withType<Task>().named { it == "jvmTest" }.configureEach {
    hourPrefixes.forEach { hourPrefix ->
        (0..59).forEach { minute ->
            outputs.file(
                minuteDataDirectory.get().file("$hourPrefix:${"%02d".format(minute)}.data")
            )
        }
    }
}

private data class ConsolidatedHourGroup(
    val name: String,
    val hourPrefixes: List<String>,
)

private val consolidatedHourGroups = listOf(
    ConsolidatedHourGroup("hours_00_02", listOf("00", "01", "02")),
    ConsolidatedHourGroup("hours_03_05", listOf("03", "04", "05")),
    ConsolidatedHourGroup("hours_06_08", listOf("06", "07", "08")),
    ConsolidatedHourGroup("hours_09_11", listOf("09", "10", "11")),
    ConsolidatedHourGroup("hours_12_14", listOf("12", "13", "14")),
    ConsolidatedHourGroup("hours_15_17", listOf("15", "16", "17")),
    ConsolidatedHourGroup("hours_18_20", listOf("18", "19", "20")),
    ConsolidatedHourGroup("hours_21_23", listOf("21", "22", "23")),
    ConsolidatedHourGroup("hours_1_3", listOf("_1", "_2", "_3")),
    ConsolidatedHourGroup("hours_4_6", listOf("_4", "_5", "_6")),
    ConsolidatedHourGroup("hours_7_9", listOf("_7", "_8", "_9")),
)

androidComponents {
    consolidatedHourGroups.forEach { group ->
        val taskName = "build" + group.name.split("_").joinToString("") { it.capitalized() } + "Otf"
        val buildGroupOtf = tasks.register(taskName, BuildConsolidatedHourOtf::class) {
            // Minute data files are generated by the jvm tests
            dependsOn("jvmTest")
            minuteDataInputDirectory = minuteDataDirectory
            groupName = group.name
            hourPrefixesInput = group.hourPrefixes.joinToString(",")
            buildScript = layout.projectDirectory.file("scripts/build_consolidated_hour_otf.py")
            generatedResDirectory = layout.buildDirectory.dir("generated/wff/res")
        }
        onVariants { variant ->
            val capitalizedVariantName = variant.name.capitalized()
            tasks.withType<Task>().named {
                it == "generate${capitalizedVariantName}ResValues" ||
                    it == "process${capitalizedVariantName}NavigationResources"
            }.configureEach {
                dependsOn(buildGroupOtf)
            }
            variant.sources.res!!.addGeneratedSourceDirectory(
                buildGroupOtf,
                BuildConsolidatedHourOtf::generatedResDirectory,
            )
        }
    }
}

abstract class BuildConsolidatedHourOtf : DefaultTask() {

    @get:InputDirectory
    abstract val minuteDataInputDirectory: DirectoryProperty

    @get:InputFile
    abstract val buildScript: RegularFileProperty

    @get:Input
    abstract val groupName: Property<String>

    @get:Input
    abstract val hourPrefixesInput: Property<String>

    @get:OutputDirectory
    abstract val generatedResDirectory: DirectoryProperty

    @get:OutputFile
    val otfFile: Provider<RegularFile> =
        generatedResDirectory.flatMap { outputDirectory ->
            groupName.map {
                outputDirectory.dir("font").file("$it.otf")
            }
        }

    @get:Inject
    abstract val execOperations: ExecOperations

    @TaskAction
    fun taskAction() {
        val result = execOperations.exec {
            commandLine(
                listOf(
                    "python3",
                    buildScript.get().asFile.absolutePath,
                    "--hour-prefixes",
                    hourPrefixesInput.get(),
                    "--font-name",
                    groupName.get(),
                    "--minute-dir",
                    minuteDataInputDirectory.get().asFile.absolutePath,
                    "--output-otf",
                    otfFile.get().asFile.absolutePath,
                ),
            )
        }
        result.rethrowFailure()
    }
}
