name = "Algorithm"
version = "0.1.0"
defaultTargets = ["Algorithm"]

[[lean_lib]]
name = "Algorithm"
roots = [
  "Algorithm",
  "AlgorithmDefs",
  "AlgorithmTheorems",
  "AlgorithmProofs",
  "theorems.BitComputationTheorems",
  "theorems.HashLifeTheorems",
  "theorems.MacroCellHashTheorems",
  "theorems.MacroCellTheorems",
  "theorems.PatternsTheorems",
  "theorems.PropertiesTheorems",
  "proofs.BitComputationProofs",
  "proofs.HashLifeProofs",
  "proofs.MacroCellHashProofs",
  "proofs.MacroCellProofs",
  "proofs.PatternsProofs",
  "proofs.PropertiesProofs",
]
